name: Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7e953739526488673297d770b29397efd5cf2a20
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Adjust if needed
          cache: "npm"
      - name: Install project dependencies
        run: npm ci
      - name: Install @nuxt/eslint
        run: npm install @nuxt/eslint@0.5.7 # Or latest compatible version
      - name: Run Prettier
        run: npx prettier . --write
      - name: Run ESLint
        run: npx eslint .
            
