name: Pre-Commit

permissions: read-all
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  common-setup: &common-setup
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: node
          cache: "npm"
      - name: Install project dependencies
        run: npm ci

  linting:
    runs-on: ubuntu-latest
    steps:
      <<: *common-setup
      - name: Run ESLint
        run: npx eslint .

  formatting:
    runs-on: ubuntu-latest
    steps:
      <<: *common-setup
      - name: Run Prettier
        run: npx prettier . --write

  testing:
    runs-on: ubuntu-latest
    steps:
      <<: *common-setup
      - name: Run Vitest
        run: npm run test -- --run
