name: Pre-Commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # Important for pushing changes

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: node
          cache: "npm"

      - name: Install project dependencies
        run: npm ci

      - name: Run SPDX header script
        id: spdx-script
        run: |
          if ! node scripts/spdxHeader.js; then
            echo "::error::SPDX header script failed to run"
            exit 1
          fi

      - name: Check for changes
        id: git-check
        if: success() && steps.spdx-script.outcome == 'success'
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npx prettier . --write

      - name: Run Vitest
        run: npm run test -- --run

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Add SPDX headers and formatting changes"
          git push origin main # Or appropriate branch
