name: Add SPDX Headers
permissions: read-all
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  add-headers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: node
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run SPDX header script
        id: spdx-script
        run: |
          if ! node scripts/spdxHeader; then
            echo "::error::SPDX header script failed to run"
            exit 1
          fi

      - name: Check for changes
        id: git-check
        if: success() && steps.spdx-script.outcome == 'success'
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          BRANCH_NAME="spdx-header-fix-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add missing SPDX headers"
          git push origin $BRANCH_NAME
