name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@7e953739526488673297d770b29397efd5cf2a20

      - name: Set up Node.js
        uses: actions/setup-node@7e953739526488673297d770b29397efd5cf2a20
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test -- --run
